/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as PortalTrafficRouteImport } from './routes/portal.traffic'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalRetentionRouteImport } from './routes/portal.retention'
import { Route as PortalOverviewRouteImport } from './routes/portal.overview'
import { Route as PortalLoyaltyRouteImport } from './routes/portal.loyalty'
import { Route as PortalLogisticsRouteImport } from './routes/portal.logistics'
import { Route as PortalCatalogRouteImport } from './routes/portal.catalog'
import { Route as PortalAnalyticsRouteImport } from './routes/portal.analytics'
import { Route as OpsReceivingRouteImport } from './routes/ops.receiving'
import { Route as OpsPickingRouteImport } from './routes/ops.picking'
import { Route as OpsPackingRouteImport } from './routes/ops.packing'
import { Route as OpsDispatchRouteImport } from './routes/ops.dispatch'
import { Route as MinhaContaTokenRouteImport } from './routes/minha-conta.$token'
import { Route as DashboardTrafficRouteImport } from './routes/_dashboard.traffic'
import { Route as DashboardSuccessRouteImport } from './routes/_dashboard.success'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardRetentionRouteImport } from './routes/_dashboard.retention'
import { Route as DashboardOverviewRouteImport } from './routes/_dashboard.overview'
import { Route as DashboardLogisticsRouteImport } from './routes/_dashboard.logistics'
import { Route as DashboardFiscalRouteImport } from './routes/_dashboard.fiscal'
import { Route as DashboardClientsRouteImport } from './routes/_dashboard.clients'
import { Route as DashboardChannelsRouteImport } from './routes/_dashboard.channels'
import { Route as DashboardCatalogRouteImport } from './routes/_dashboard.catalog'
import { Route as DashboardBillingRouteImport } from './routes/_dashboard.billing'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as ApiWebhooksTiktokRouteImport } from './routes/api/webhooks/tiktok'
import { Route as ApiWebhooksShopifyRouteImport } from './routes/api/webhooks/shopify'
import { Route as ApiWebhooksShopeeRouteImport } from './routes/api/webhooks/shopee'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiWebhooksPagarMeRouteImport } from './routes/api/webhooks/pagar-me'
import { Route as ApiWebhooksNuvemshopRouteImport } from './routes/api/webhooks/nuvemshop'
import { Route as ApiWebhooksMercadoPagoRouteImport } from './routes/api/webhooks/mercado-pago'
import { Route as ApiWebhooksMercadoLivreRouteImport } from './routes/api/webhooks/mercado-livre'
import { Route as ApiWebhooksMelhorEnvioRouteImport } from './routes/api/webhooks/melhor-envio'
import { Route as ApiWebhooksInstagramRouteImport } from './routes/api/webhooks/instagram'
import { Route as ApiWebhooksEvolutionRouteImport } from './routes/api/webhooks/evolution'
import { Route as ApiWebhooksAmazonRouteImport } from './routes/api/webhooks/amazon'
import { Route as ApiCronRunRouteImport } from './routes/api/cron/run'
import { Route as DashboardLogisticsWarehouseRouteImport } from './routes/_dashboard.logistics.warehouse'
import { Route as DashboardLogisticsTrackingRouteImport } from './routes/_dashboard.logistics.tracking'
import { Route as DashboardLogisticsSlaRouteImport } from './routes/_dashboard.logistics.sla'
import { Route as DashboardLogisticsReturnsRouteImport } from './routes/_dashboard.logistics.returns'
import { Route as DashboardLogisticsReceivingRouteImport } from './routes/_dashboard.logistics.receiving'
import { Route as DashboardLogisticsQuarantineRouteImport } from './routes/_dashboard.logistics.quarantine'
import { Route as DashboardLogisticsProductsRouteImport } from './routes/_dashboard.logistics.products'
import { Route as DashboardLogisticsPickupsRouteImport } from './routes/_dashboard.logistics.pickups'
import { Route as DashboardLogisticsPickingRouteImport } from './routes/_dashboard.logistics.picking'
import { Route as DashboardLogisticsPackingRouteImport } from './routes/_dashboard.logistics.packing'
import { Route as DashboardLogisticsOpsDashboardRouteImport } from './routes/_dashboard.logistics.ops-dashboard'
import { Route as DashboardLogisticsInventoryRouteImport } from './routes/_dashboard.logistics.inventory'
import { Route as DashboardLogisticsIncidentsRouteImport } from './routes/_dashboard.logistics.incidents'
import { Route as DashboardLogisticsDispatchRouteImport } from './routes/_dashboard.logistics.dispatch'
import { Route as DashboardLogisticsCarriersRouteImport } from './routes/_dashboard.logistics.carriers'
import { Route as DashboardLogisticsAnalyticsRouteImport } from './routes/_dashboard.logistics.analytics'
import { Route as DashboardFiscalConfigRouteImport } from './routes/_dashboard.fiscal.config'
import { Route as DashboardFiscalIdRouteImport } from './routes/_dashboard.fiscal.$id'
import { Route as DashboardClientsIdRouteImport } from './routes/_dashboard.clients.$id'
import { Route as DashboardChannelsTiktokRouteImport } from './routes/_dashboard.channels.tiktok'
import { Route as DashboardChannelsShopeeRouteImport } from './routes/_dashboard.channels.shopee'
import { Route as DashboardChannelsMercadoLivreRouteImport } from './routes/_dashboard.channels.mercado-livre'
import { Route as DashboardChannelsLojasRouteImport } from './routes/_dashboard.channels.lojas'
import { Route as DashboardChannelsInstagramRouteImport } from './routes/_dashboard.channels.instagram'
import { Route as DashboardChannelsAmazonRouteImport } from './routes/_dashboard.channels.amazon'
import { Route as DashboardCatalogFiscalRouteImport } from './routes/_dashboard.catalog.fiscal'
import { Route as ApiOauthWhatsappCallbackRouteImport } from './routes/api/oauth/whatsapp/callback'
import { Route as ApiOauthTiktokCallbackRouteImport } from './routes/api/oauth/tiktok/callback'
import { Route as ApiOauthShopifyCallbackRouteImport } from './routes/api/oauth/shopify/callback'
import { Route as ApiOauthShopeeCallbackRouteImport } from './routes/api/oauth/shopee/callback'
import { Route as ApiOauthNuvemshopCallbackRouteImport } from './routes/api/oauth/nuvemshop/callback'
import { Route as ApiOauthMetaCallbackRouteImport } from './routes/api/oauth/meta/callback'
import { Route as ApiOauthMercadoLivreCallbackRouteImport } from './routes/api/oauth/mercado-livre/callback'
import { Route as ApiOauthMelhorEnvioCallbackRouteImport } from './routes/api/oauth/melhor-envio/callback'
import { Route as ApiOauthInstagramCallbackRouteImport } from './routes/api/oauth/instagram/callback'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google/callback'
import { Route as ApiOauthAmazonCallbackRouteImport } from './routes/api/oauth/amazon/callback'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const PortalTrafficRoute = PortalTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRetentionRoute = PortalRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOverviewRoute = PortalOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoyaltyRoute = PortalLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLogisticsRoute = PortalLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCatalogRoute = PortalCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnalyticsRoute = PortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortalRoute,
} as any)
const OpsReceivingRoute = OpsReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPickingRoute = OpsPickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPackingRoute = OpsPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDispatchRoute = OpsDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => OpsRoute,
} as any)
const MinhaContaTokenRoute = MinhaContaTokenRouteImport.update({
  id: '/minha-conta/$token',
  path: '/minha-conta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrafficRoute = DashboardTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuccessRoute = DashboardSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRetentionRoute = DashboardRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogisticsRoute = DashboardLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFiscalRoute = DashboardFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsRoute = DashboardChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCatalogRoute = DashboardCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTiktokRoute = ApiWebhooksTiktokRouteImport.update({
  id: '/api/webhooks/tiktok',
  path: '/api/webhooks/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksShopifyRoute = ApiWebhooksShopifyRouteImport.update({
  id: '/api/webhooks/shopify',
  path: '/api/webhooks/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksShopeeRoute = ApiWebhooksShopeeRouteImport.update({
  id: '/api/webhooks/shopee',
  path: '/api/webhooks/shopee',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPagarMeRoute = ApiWebhooksPagarMeRouteImport.update({
  id: '/api/webhooks/pagar-me',
  path: '/api/webhooks/pagar-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksNuvemshopRoute = ApiWebhooksNuvemshopRouteImport.update({
  id: '/api/webhooks/nuvemshop',
  path: '/api/webhooks/nuvemshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadoPagoRoute = ApiWebhooksMercadoPagoRouteImport.update({
  id: '/api/webhooks/mercado-pago',
  path: '/api/webhooks/mercado-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadoLivreRoute = ApiWebhooksMercadoLivreRouteImport.update({
  id: '/api/webhooks/mercado-livre',
  path: '/api/webhooks/mercado-livre',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMelhorEnvioRoute = ApiWebhooksMelhorEnvioRouteImport.update({
  id: '/api/webhooks/melhor-envio',
  path: '/api/webhooks/melhor-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksInstagramRoute = ApiWebhooksInstagramRouteImport.update({
  id: '/api/webhooks/instagram',
  path: '/api/webhooks/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksEvolutionRoute = ApiWebhooksEvolutionRouteImport.update({
  id: '/api/webhooks/evolution',
  path: '/api/webhooks/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksAmazonRoute = ApiWebhooksAmazonRouteImport.update({
  id: '/api/webhooks/amazon',
  path: '/api/webhooks/amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRunRoute = ApiCronRunRouteImport.update({
  id: '/api/cron/run',
  path: '/api/cron/run',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLogisticsWarehouseRoute =
  DashboardLogisticsWarehouseRouteImport.update({
    id: '/warehouse',
    path: '/warehouse',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsTrackingRoute =
  DashboardLogisticsTrackingRouteImport.update({
    id: '/tracking',
    path: '/tracking',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsSlaRoute = DashboardLogisticsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => DashboardLogisticsRoute,
} as any)
const DashboardLogisticsReturnsRoute =
  DashboardLogisticsReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsReceivingRoute =
  DashboardLogisticsReceivingRouteImport.update({
    id: '/receiving',
    path: '/receiving',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsQuarantineRoute =
  DashboardLogisticsQuarantineRouteImport.update({
    id: '/quarantine',
    path: '/quarantine',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsProductsRoute =
  DashboardLogisticsProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsPickupsRoute =
  DashboardLogisticsPickupsRouteImport.update({
    id: '/pickups',
    path: '/pickups',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsPickingRoute =
  DashboardLogisticsPickingRouteImport.update({
    id: '/picking',
    path: '/picking',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsPackingRoute =
  DashboardLogisticsPackingRouteImport.update({
    id: '/packing',
    path: '/packing',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsOpsDashboardRoute =
  DashboardLogisticsOpsDashboardRouteImport.update({
    id: '/ops-dashboard',
    path: '/ops-dashboard',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsInventoryRoute =
  DashboardLogisticsInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsIncidentsRoute =
  DashboardLogisticsIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsDispatchRoute =
  DashboardLogisticsDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsCarriersRoute =
  DashboardLogisticsCarriersRouteImport.update({
    id: '/carriers',
    path: '/carriers',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardLogisticsAnalyticsRoute =
  DashboardLogisticsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardLogisticsRoute,
  } as any)
const DashboardFiscalConfigRoute = DashboardFiscalConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardFiscalRoute,
} as any)
const DashboardFiscalIdRoute = DashboardFiscalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardFiscalRoute,
} as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardClientsRoute,
} as any)
const DashboardChannelsTiktokRoute = DashboardChannelsTiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => DashboardChannelsRoute,
} as any)
const DashboardChannelsShopeeRoute = DashboardChannelsShopeeRouteImport.update({
  id: '/shopee',
  path: '/shopee',
  getParentRoute: () => DashboardChannelsRoute,
} as any)
const DashboardChannelsMercadoLivreRoute =
  DashboardChannelsMercadoLivreRouteImport.update({
    id: '/mercado-livre',
    path: '/mercado-livre',
    getParentRoute: () => DashboardChannelsRoute,
  } as any)
const DashboardChannelsLojasRoute = DashboardChannelsLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => DashboardChannelsRoute,
} as any)
const DashboardChannelsInstagramRoute =
  DashboardChannelsInstagramRouteImport.update({
    id: '/instagram',
    path: '/instagram',
    getParentRoute: () => DashboardChannelsRoute,
  } as any)
const DashboardChannelsAmazonRoute = DashboardChannelsAmazonRouteImport.update({
  id: '/amazon',
  path: '/amazon',
  getParentRoute: () => DashboardChannelsRoute,
} as any)
const DashboardCatalogFiscalRoute = DashboardCatalogFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => DashboardCatalogRoute,
} as any)
const ApiOauthWhatsappCallbackRoute =
  ApiOauthWhatsappCallbackRouteImport.update({
    id: '/api/oauth/whatsapp/callback',
    path: '/api/oauth/whatsapp/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthTiktokCallbackRoute = ApiOauthTiktokCallbackRouteImport.update({
  id: '/api/oauth/tiktok/callback',
  path: '/api/oauth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthShopifyCallbackRoute = ApiOauthShopifyCallbackRouteImport.update({
  id: '/api/oauth/shopify/callback',
  path: '/api/oauth/shopify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthShopeeCallbackRoute = ApiOauthShopeeCallbackRouteImport.update({
  id: '/api/oauth/shopee/callback',
  path: '/api/oauth/shopee/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthNuvemshopCallbackRoute =
  ApiOauthNuvemshopCallbackRouteImport.update({
    id: '/api/oauth/nuvemshop/callback',
    path: '/api/oauth/nuvemshop/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthMetaCallbackRoute = ApiOauthMetaCallbackRouteImport.update({
  id: '/api/oauth/meta/callback',
  path: '/api/oauth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthMercadoLivreCallbackRoute =
  ApiOauthMercadoLivreCallbackRouteImport.update({
    id: '/api/oauth/mercado-livre/callback',
    path: '/api/oauth/mercado-livre/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthMelhorEnvioCallbackRoute =
  ApiOauthMelhorEnvioCallbackRouteImport.update({
    id: '/api/oauth/melhor-envio/callback',
    path: '/api/oauth/melhor-envio/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthInstagramCallbackRoute =
  ApiOauthInstagramCallbackRouteImport.update({
    id: '/api/oauth/instagram/callback',
    path: '/api/oauth/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthAmazonCallbackRoute = ApiOauthAmazonCallbackRouteImport.update({
  id: '/api/oauth/amazon/callback',
  path: '/api/oauth/amazon/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/analytics': typeof DashboardAnalyticsRoute
  '/billing': typeof DashboardBillingRoute
  '/catalog': typeof DashboardCatalogRouteWithChildren
  '/channels': typeof DashboardChannelsRouteWithChildren
  '/clients': typeof DashboardClientsRouteWithChildren
  '/fiscal': typeof DashboardFiscalRouteWithChildren
  '/logistics': typeof DashboardLogisticsRouteWithChildren
  '/overview': typeof DashboardOverviewRoute
  '/retention': typeof DashboardRetentionRoute
  '/settings': typeof DashboardSettingsRoute
  '/success': typeof DashboardSuccessRoute
  '/traffic': typeof DashboardTrafficRoute
  '/minha-conta/$token': typeof MinhaContaTokenRoute
  '/ops/dispatch': typeof OpsDispatchRoute
  '/ops/packing': typeof OpsPackingRoute
  '/ops/picking': typeof OpsPickingRoute
  '/ops/receiving': typeof OpsReceivingRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/loyalty': typeof PortalLoyaltyRoute
  '/portal/overview': typeof PortalOverviewRoute
  '/portal/retention': typeof PortalRetentionRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/traffic': typeof PortalTrafficRoute
  '/ops/': typeof OpsIndexRoute
  '/catalog/fiscal': typeof DashboardCatalogFiscalRoute
  '/channels/amazon': typeof DashboardChannelsAmazonRoute
  '/channels/instagram': typeof DashboardChannelsInstagramRoute
  '/channels/lojas': typeof DashboardChannelsLojasRoute
  '/channels/mercado-livre': typeof DashboardChannelsMercadoLivreRoute
  '/channels/shopee': typeof DashboardChannelsShopeeRoute
  '/channels/tiktok': typeof DashboardChannelsTiktokRoute
  '/clients/$id': typeof DashboardClientsIdRoute
  '/fiscal/$id': typeof DashboardFiscalIdRoute
  '/fiscal/config': typeof DashboardFiscalConfigRoute
  '/logistics/analytics': typeof DashboardLogisticsAnalyticsRoute
  '/logistics/carriers': typeof DashboardLogisticsCarriersRoute
  '/logistics/dispatch': typeof DashboardLogisticsDispatchRoute
  '/logistics/incidents': typeof DashboardLogisticsIncidentsRoute
  '/logistics/inventory': typeof DashboardLogisticsInventoryRoute
  '/logistics/ops-dashboard': typeof DashboardLogisticsOpsDashboardRoute
  '/logistics/packing': typeof DashboardLogisticsPackingRoute
  '/logistics/picking': typeof DashboardLogisticsPickingRoute
  '/logistics/pickups': typeof DashboardLogisticsPickupsRoute
  '/logistics/products': typeof DashboardLogisticsProductsRoute
  '/logistics/quarantine': typeof DashboardLogisticsQuarantineRoute
  '/logistics/receiving': typeof DashboardLogisticsReceivingRoute
  '/logistics/returns': typeof DashboardLogisticsReturnsRoute
  '/logistics/sla': typeof DashboardLogisticsSlaRoute
  '/logistics/tracking': typeof DashboardLogisticsTrackingRoute
  '/logistics/warehouse': typeof DashboardLogisticsWarehouseRoute
  '/api/cron/run': typeof ApiCronRunRoute
  '/api/webhooks/amazon': typeof ApiWebhooksAmazonRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/melhor-envio': typeof ApiWebhooksMelhorEnvioRoute
  '/api/webhooks/mercado-livre': typeof ApiWebhooksMercadoLivreRoute
  '/api/webhooks/mercado-pago': typeof ApiWebhooksMercadoPagoRoute
  '/api/webhooks/nuvemshop': typeof ApiWebhooksNuvemshopRoute
  '/api/webhooks/pagar-me': typeof ApiWebhooksPagarMeRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/webhooks/shopee': typeof ApiWebhooksShopeeRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/api/webhooks/tiktok': typeof ApiWebhooksTiktokRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/amazon/callback': typeof ApiOauthAmazonCallbackRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/instagram/callback': typeof ApiOauthInstagramCallbackRoute
  '/api/oauth/melhor-envio/callback': typeof ApiOauthMelhorEnvioCallbackRoute
  '/api/oauth/mercado-livre/callback': typeof ApiOauthMercadoLivreCallbackRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/nuvemshop/callback': typeof ApiOauthNuvemshopCallbackRoute
  '/api/oauth/shopee/callback': typeof ApiOauthShopeeCallbackRoute
  '/api/oauth/shopify/callback': typeof ApiOauthShopifyCallbackRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/whatsapp/callback': typeof ApiOauthWhatsappCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/analytics': typeof DashboardAnalyticsRoute
  '/billing': typeof DashboardBillingRoute
  '/catalog': typeof DashboardCatalogRouteWithChildren
  '/channels': typeof DashboardChannelsRouteWithChildren
  '/clients': typeof DashboardClientsRouteWithChildren
  '/fiscal': typeof DashboardFiscalRouteWithChildren
  '/logistics': typeof DashboardLogisticsRouteWithChildren
  '/overview': typeof DashboardOverviewRoute
  '/retention': typeof DashboardRetentionRoute
  '/settings': typeof DashboardSettingsRoute
  '/success': typeof DashboardSuccessRoute
  '/traffic': typeof DashboardTrafficRoute
  '/minha-conta/$token': typeof MinhaContaTokenRoute
  '/ops/dispatch': typeof OpsDispatchRoute
  '/ops/packing': typeof OpsPackingRoute
  '/ops/picking': typeof OpsPickingRoute
  '/ops/receiving': typeof OpsReceivingRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/loyalty': typeof PortalLoyaltyRoute
  '/portal/overview': typeof PortalOverviewRoute
  '/portal/retention': typeof PortalRetentionRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/traffic': typeof PortalTrafficRoute
  '/ops': typeof OpsIndexRoute
  '/catalog/fiscal': typeof DashboardCatalogFiscalRoute
  '/channels/amazon': typeof DashboardChannelsAmazonRoute
  '/channels/instagram': typeof DashboardChannelsInstagramRoute
  '/channels/lojas': typeof DashboardChannelsLojasRoute
  '/channels/mercado-livre': typeof DashboardChannelsMercadoLivreRoute
  '/channels/shopee': typeof DashboardChannelsShopeeRoute
  '/channels/tiktok': typeof DashboardChannelsTiktokRoute
  '/clients/$id': typeof DashboardClientsIdRoute
  '/fiscal/$id': typeof DashboardFiscalIdRoute
  '/fiscal/config': typeof DashboardFiscalConfigRoute
  '/logistics/analytics': typeof DashboardLogisticsAnalyticsRoute
  '/logistics/carriers': typeof DashboardLogisticsCarriersRoute
  '/logistics/dispatch': typeof DashboardLogisticsDispatchRoute
  '/logistics/incidents': typeof DashboardLogisticsIncidentsRoute
  '/logistics/inventory': typeof DashboardLogisticsInventoryRoute
  '/logistics/ops-dashboard': typeof DashboardLogisticsOpsDashboardRoute
  '/logistics/packing': typeof DashboardLogisticsPackingRoute
  '/logistics/picking': typeof DashboardLogisticsPickingRoute
  '/logistics/pickups': typeof DashboardLogisticsPickupsRoute
  '/logistics/products': typeof DashboardLogisticsProductsRoute
  '/logistics/quarantine': typeof DashboardLogisticsQuarantineRoute
  '/logistics/receiving': typeof DashboardLogisticsReceivingRoute
  '/logistics/returns': typeof DashboardLogisticsReturnsRoute
  '/logistics/sla': typeof DashboardLogisticsSlaRoute
  '/logistics/tracking': typeof DashboardLogisticsTrackingRoute
  '/logistics/warehouse': typeof DashboardLogisticsWarehouseRoute
  '/api/cron/run': typeof ApiCronRunRoute
  '/api/webhooks/amazon': typeof ApiWebhooksAmazonRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/melhor-envio': typeof ApiWebhooksMelhorEnvioRoute
  '/api/webhooks/mercado-livre': typeof ApiWebhooksMercadoLivreRoute
  '/api/webhooks/mercado-pago': typeof ApiWebhooksMercadoPagoRoute
  '/api/webhooks/nuvemshop': typeof ApiWebhooksNuvemshopRoute
  '/api/webhooks/pagar-me': typeof ApiWebhooksPagarMeRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/webhooks/shopee': typeof ApiWebhooksShopeeRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/api/webhooks/tiktok': typeof ApiWebhooksTiktokRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/amazon/callback': typeof ApiOauthAmazonCallbackRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/instagram/callback': typeof ApiOauthInstagramCallbackRoute
  '/api/oauth/melhor-envio/callback': typeof ApiOauthMelhorEnvioCallbackRoute
  '/api/oauth/mercado-livre/callback': typeof ApiOauthMercadoLivreCallbackRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/nuvemshop/callback': typeof ApiOauthNuvemshopCallbackRoute
  '/api/oauth/shopee/callback': typeof ApiOauthShopeeCallbackRoute
  '/api/oauth/shopify/callback': typeof ApiOauthShopifyCallbackRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/whatsapp/callback': typeof ApiOauthWhatsappCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/catalog': typeof DashboardCatalogRouteWithChildren
  '/_dashboard/channels': typeof DashboardChannelsRouteWithChildren
  '/_dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/_dashboard/fiscal': typeof DashboardFiscalRouteWithChildren
  '/_dashboard/logistics': typeof DashboardLogisticsRouteWithChildren
  '/_dashboard/overview': typeof DashboardOverviewRoute
  '/_dashboard/retention': typeof DashboardRetentionRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/success': typeof DashboardSuccessRoute
  '/_dashboard/traffic': typeof DashboardTrafficRoute
  '/minha-conta/$token': typeof MinhaContaTokenRoute
  '/ops/dispatch': typeof OpsDispatchRoute
  '/ops/packing': typeof OpsPackingRoute
  '/ops/picking': typeof OpsPickingRoute
  '/ops/receiving': typeof OpsReceivingRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/loyalty': typeof PortalLoyaltyRoute
  '/portal/overview': typeof PortalOverviewRoute
  '/portal/retention': typeof PortalRetentionRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/traffic': typeof PortalTrafficRoute
  '/ops/': typeof OpsIndexRoute
  '/_dashboard/catalog/fiscal': typeof DashboardCatalogFiscalRoute
  '/_dashboard/channels/amazon': typeof DashboardChannelsAmazonRoute
  '/_dashboard/channels/instagram': typeof DashboardChannelsInstagramRoute
  '/_dashboard/channels/lojas': typeof DashboardChannelsLojasRoute
  '/_dashboard/channels/mercado-livre': typeof DashboardChannelsMercadoLivreRoute
  '/_dashboard/channels/shopee': typeof DashboardChannelsShopeeRoute
  '/_dashboard/channels/tiktok': typeof DashboardChannelsTiktokRoute
  '/_dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/_dashboard/fiscal/$id': typeof DashboardFiscalIdRoute
  '/_dashboard/fiscal/config': typeof DashboardFiscalConfigRoute
  '/_dashboard/logistics/analytics': typeof DashboardLogisticsAnalyticsRoute
  '/_dashboard/logistics/carriers': typeof DashboardLogisticsCarriersRoute
  '/_dashboard/logistics/dispatch': typeof DashboardLogisticsDispatchRoute
  '/_dashboard/logistics/incidents': typeof DashboardLogisticsIncidentsRoute
  '/_dashboard/logistics/inventory': typeof DashboardLogisticsInventoryRoute
  '/_dashboard/logistics/ops-dashboard': typeof DashboardLogisticsOpsDashboardRoute
  '/_dashboard/logistics/packing': typeof DashboardLogisticsPackingRoute
  '/_dashboard/logistics/picking': typeof DashboardLogisticsPickingRoute
  '/_dashboard/logistics/pickups': typeof DashboardLogisticsPickupsRoute
  '/_dashboard/logistics/products': typeof DashboardLogisticsProductsRoute
  '/_dashboard/logistics/quarantine': typeof DashboardLogisticsQuarantineRoute
  '/_dashboard/logistics/receiving': typeof DashboardLogisticsReceivingRoute
  '/_dashboard/logistics/returns': typeof DashboardLogisticsReturnsRoute
  '/_dashboard/logistics/sla': typeof DashboardLogisticsSlaRoute
  '/_dashboard/logistics/tracking': typeof DashboardLogisticsTrackingRoute
  '/_dashboard/logistics/warehouse': typeof DashboardLogisticsWarehouseRoute
  '/api/cron/run': typeof ApiCronRunRoute
  '/api/webhooks/amazon': typeof ApiWebhooksAmazonRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/melhor-envio': typeof ApiWebhooksMelhorEnvioRoute
  '/api/webhooks/mercado-livre': typeof ApiWebhooksMercadoLivreRoute
  '/api/webhooks/mercado-pago': typeof ApiWebhooksMercadoPagoRoute
  '/api/webhooks/nuvemshop': typeof ApiWebhooksNuvemshopRoute
  '/api/webhooks/pagar-me': typeof ApiWebhooksPagarMeRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/webhooks/shopee': typeof ApiWebhooksShopeeRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/api/webhooks/tiktok': typeof ApiWebhooksTiktokRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/amazon/callback': typeof ApiOauthAmazonCallbackRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/instagram/callback': typeof ApiOauthInstagramCallbackRoute
  '/api/oauth/melhor-envio/callback': typeof ApiOauthMelhorEnvioCallbackRoute
  '/api/oauth/mercado-livre/callback': typeof ApiOauthMercadoLivreCallbackRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/nuvemshop/callback': typeof ApiOauthNuvemshopCallbackRoute
  '/api/oauth/shopee/callback': typeof ApiOauthShopeeCallbackRoute
  '/api/oauth/shopify/callback': typeof ApiOauthShopifyCallbackRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/whatsapp/callback': typeof ApiOauthWhatsappCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ops'
    | '/portal'
    | '/analytics'
    | '/billing'
    | '/catalog'
    | '/channels'
    | '/clients'
    | '/fiscal'
    | '/logistics'
    | '/overview'
    | '/retention'
    | '/settings'
    | '/success'
    | '/traffic'
    | '/minha-conta/$token'
    | '/ops/dispatch'
    | '/ops/packing'
    | '/ops/picking'
    | '/ops/receiving'
    | '/portal/analytics'
    | '/portal/catalog'
    | '/portal/logistics'
    | '/portal/loyalty'
    | '/portal/overview'
    | '/portal/retention'
    | '/portal/settings'
    | '/portal/traffic'
    | '/ops/'
    | '/catalog/fiscal'
    | '/channels/amazon'
    | '/channels/instagram'
    | '/channels/lojas'
    | '/channels/mercado-livre'
    | '/channels/shopee'
    | '/channels/tiktok'
    | '/clients/$id'
    | '/fiscal/$id'
    | '/fiscal/config'
    | '/logistics/analytics'
    | '/logistics/carriers'
    | '/logistics/dispatch'
    | '/logistics/incidents'
    | '/logistics/inventory'
    | '/logistics/ops-dashboard'
    | '/logistics/packing'
    | '/logistics/picking'
    | '/logistics/pickups'
    | '/logistics/products'
    | '/logistics/quarantine'
    | '/logistics/receiving'
    | '/logistics/returns'
    | '/logistics/sla'
    | '/logistics/tracking'
    | '/logistics/warehouse'
    | '/api/cron/run'
    | '/api/webhooks/amazon'
    | '/api/webhooks/evolution'
    | '/api/webhooks/instagram'
    | '/api/webhooks/melhor-envio'
    | '/api/webhooks/mercado-livre'
    | '/api/webhooks/mercado-pago'
    | '/api/webhooks/nuvemshop'
    | '/api/webhooks/pagar-me'
    | '/api/webhooks/resend'
    | '/api/webhooks/shopee'
    | '/api/webhooks/shopify'
    | '/api/webhooks/tiktok'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/amazon/callback'
    | '/api/oauth/google/callback'
    | '/api/oauth/instagram/callback'
    | '/api/oauth/melhor-envio/callback'
    | '/api/oauth/mercado-livre/callback'
    | '/api/oauth/meta/callback'
    | '/api/oauth/nuvemshop/callback'
    | '/api/oauth/shopee/callback'
    | '/api/oauth/shopify/callback'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/whatsapp/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/analytics'
    | '/billing'
    | '/catalog'
    | '/channels'
    | '/clients'
    | '/fiscal'
    | '/logistics'
    | '/overview'
    | '/retention'
    | '/settings'
    | '/success'
    | '/traffic'
    | '/minha-conta/$token'
    | '/ops/dispatch'
    | '/ops/packing'
    | '/ops/picking'
    | '/ops/receiving'
    | '/portal/analytics'
    | '/portal/catalog'
    | '/portal/logistics'
    | '/portal/loyalty'
    | '/portal/overview'
    | '/portal/retention'
    | '/portal/settings'
    | '/portal/traffic'
    | '/ops'
    | '/catalog/fiscal'
    | '/channels/amazon'
    | '/channels/instagram'
    | '/channels/lojas'
    | '/channels/mercado-livre'
    | '/channels/shopee'
    | '/channels/tiktok'
    | '/clients/$id'
    | '/fiscal/$id'
    | '/fiscal/config'
    | '/logistics/analytics'
    | '/logistics/carriers'
    | '/logistics/dispatch'
    | '/logistics/incidents'
    | '/logistics/inventory'
    | '/logistics/ops-dashboard'
    | '/logistics/packing'
    | '/logistics/picking'
    | '/logistics/pickups'
    | '/logistics/products'
    | '/logistics/quarantine'
    | '/logistics/receiving'
    | '/logistics/returns'
    | '/logistics/sla'
    | '/logistics/tracking'
    | '/logistics/warehouse'
    | '/api/cron/run'
    | '/api/webhooks/amazon'
    | '/api/webhooks/evolution'
    | '/api/webhooks/instagram'
    | '/api/webhooks/melhor-envio'
    | '/api/webhooks/mercado-livre'
    | '/api/webhooks/mercado-pago'
    | '/api/webhooks/nuvemshop'
    | '/api/webhooks/pagar-me'
    | '/api/webhooks/resend'
    | '/api/webhooks/shopee'
    | '/api/webhooks/shopify'
    | '/api/webhooks/tiktok'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/amazon/callback'
    | '/api/oauth/google/callback'
    | '/api/oauth/instagram/callback'
    | '/api/oauth/melhor-envio/callback'
    | '/api/oauth/mercado-livre/callback'
    | '/api/oauth/meta/callback'
    | '/api/oauth/nuvemshop/callback'
    | '/api/oauth/shopee/callback'
    | '/api/oauth/shopify/callback'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/whatsapp/callback'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/ops'
    | '/portal'
    | '/_dashboard/analytics'
    | '/_dashboard/billing'
    | '/_dashboard/catalog'
    | '/_dashboard/channels'
    | '/_dashboard/clients'
    | '/_dashboard/fiscal'
    | '/_dashboard/logistics'
    | '/_dashboard/overview'
    | '/_dashboard/retention'
    | '/_dashboard/settings'
    | '/_dashboard/success'
    | '/_dashboard/traffic'
    | '/minha-conta/$token'
    | '/ops/dispatch'
    | '/ops/packing'
    | '/ops/picking'
    | '/ops/receiving'
    | '/portal/analytics'
    | '/portal/catalog'
    | '/portal/logistics'
    | '/portal/loyalty'
    | '/portal/overview'
    | '/portal/retention'
    | '/portal/settings'
    | '/portal/traffic'
    | '/ops/'
    | '/_dashboard/catalog/fiscal'
    | '/_dashboard/channels/amazon'
    | '/_dashboard/channels/instagram'
    | '/_dashboard/channels/lojas'
    | '/_dashboard/channels/mercado-livre'
    | '/_dashboard/channels/shopee'
    | '/_dashboard/channels/tiktok'
    | '/_dashboard/clients/$id'
    | '/_dashboard/fiscal/$id'
    | '/_dashboard/fiscal/config'
    | '/_dashboard/logistics/analytics'
    | '/_dashboard/logistics/carriers'
    | '/_dashboard/logistics/dispatch'
    | '/_dashboard/logistics/incidents'
    | '/_dashboard/logistics/inventory'
    | '/_dashboard/logistics/ops-dashboard'
    | '/_dashboard/logistics/packing'
    | '/_dashboard/logistics/picking'
    | '/_dashboard/logistics/pickups'
    | '/_dashboard/logistics/products'
    | '/_dashboard/logistics/quarantine'
    | '/_dashboard/logistics/receiving'
    | '/_dashboard/logistics/returns'
    | '/_dashboard/logistics/sla'
    | '/_dashboard/logistics/tracking'
    | '/_dashboard/logistics/warehouse'
    | '/api/cron/run'
    | '/api/webhooks/amazon'
    | '/api/webhooks/evolution'
    | '/api/webhooks/instagram'
    | '/api/webhooks/melhor-envio'
    | '/api/webhooks/mercado-livre'
    | '/api/webhooks/mercado-pago'
    | '/api/webhooks/nuvemshop'
    | '/api/webhooks/pagar-me'
    | '/api/webhooks/resend'
    | '/api/webhooks/shopee'
    | '/api/webhooks/shopify'
    | '/api/webhooks/tiktok'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/amazon/callback'
    | '/api/oauth/google/callback'
    | '/api/oauth/instagram/callback'
    | '/api/oauth/melhor-envio/callback'
    | '/api/oauth/mercado-livre/callback'
    | '/api/oauth/meta/callback'
    | '/api/oauth/nuvemshop/callback'
    | '/api/oauth/shopee/callback'
    | '/api/oauth/shopify/callback'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/whatsapp/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  MinhaContaTokenRoute: typeof MinhaContaTokenRoute
  ApiCronRunRoute: typeof ApiCronRunRoute
  ApiWebhooksAmazonRoute: typeof ApiWebhooksAmazonRoute
  ApiWebhooksEvolutionRoute: typeof ApiWebhooksEvolutionRoute
  ApiWebhooksInstagramRoute: typeof ApiWebhooksInstagramRoute
  ApiWebhooksMelhorEnvioRoute: typeof ApiWebhooksMelhorEnvioRoute
  ApiWebhooksMercadoLivreRoute: typeof ApiWebhooksMercadoLivreRoute
  ApiWebhooksMercadoPagoRoute: typeof ApiWebhooksMercadoPagoRoute
  ApiWebhooksNuvemshopRoute: typeof ApiWebhooksNuvemshopRoute
  ApiWebhooksPagarMeRoute: typeof ApiWebhooksPagarMeRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
  ApiWebhooksShopeeRoute: typeof ApiWebhooksShopeeRoute
  ApiWebhooksShopifyRoute: typeof ApiWebhooksShopifyRoute
  ApiWebhooksTiktokRoute: typeof ApiWebhooksTiktokRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
  ApiOauthAmazonCallbackRoute: typeof ApiOauthAmazonCallbackRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthInstagramCallbackRoute: typeof ApiOauthInstagramCallbackRoute
  ApiOauthMelhorEnvioCallbackRoute: typeof ApiOauthMelhorEnvioCallbackRoute
  ApiOauthMercadoLivreCallbackRoute: typeof ApiOauthMercadoLivreCallbackRoute
  ApiOauthMetaCallbackRoute: typeof ApiOauthMetaCallbackRoute
  ApiOauthNuvemshopCallbackRoute: typeof ApiOauthNuvemshopCallbackRoute
  ApiOauthShopeeCallbackRoute: typeof ApiOauthShopeeCallbackRoute
  ApiOauthShopifyCallbackRoute: typeof ApiOauthShopifyCallbackRoute
  ApiOauthTiktokCallbackRoute: typeof ApiOauthTiktokCallbackRoute
  ApiOauthWhatsappCallbackRoute: typeof ApiOauthWhatsappCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/portal/traffic': {
      id: '/portal/traffic'
      path: '/traffic'
      fullPath: '/portal/traffic'
      preLoaderRoute: typeof PortalTrafficRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/retention': {
      id: '/portal/retention'
      path: '/retention'
      fullPath: '/portal/retention'
      preLoaderRoute: typeof PortalRetentionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/overview': {
      id: '/portal/overview'
      path: '/overview'
      fullPath: '/portal/overview'
      preLoaderRoute: typeof PortalOverviewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/loyalty': {
      id: '/portal/loyalty'
      path: '/loyalty'
      fullPath: '/portal/loyalty'
      preLoaderRoute: typeof PortalLoyaltyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/logistics': {
      id: '/portal/logistics'
      path: '/logistics'
      fullPath: '/portal/logistics'
      preLoaderRoute: typeof PortalLogisticsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/catalog': {
      id: '/portal/catalog'
      path: '/catalog'
      fullPath: '/portal/catalog'
      preLoaderRoute: typeof PortalCatalogRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/analytics': {
      id: '/portal/analytics'
      path: '/analytics'
      fullPath: '/portal/analytics'
      preLoaderRoute: typeof PortalAnalyticsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/ops/receiving': {
      id: '/ops/receiving'
      path: '/receiving'
      fullPath: '/ops/receiving'
      preLoaderRoute: typeof OpsReceivingRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/picking': {
      id: '/ops/picking'
      path: '/picking'
      fullPath: '/ops/picking'
      preLoaderRoute: typeof OpsPickingRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/packing': {
      id: '/ops/packing'
      path: '/packing'
      fullPath: '/ops/packing'
      preLoaderRoute: typeof OpsPackingRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/dispatch': {
      id: '/ops/dispatch'
      path: '/dispatch'
      fullPath: '/ops/dispatch'
      preLoaderRoute: typeof OpsDispatchRouteImport
      parentRoute: typeof OpsRoute
    }
    '/minha-conta/$token': {
      id: '/minha-conta/$token'
      path: '/minha-conta/$token'
      fullPath: '/minha-conta/$token'
      preLoaderRoute: typeof MinhaContaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/traffic': {
      id: '/_dashboard/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof DashboardTrafficRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/success': {
      id: '/_dashboard/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof DashboardSuccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/retention': {
      id: '/_dashboard/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof DashboardRetentionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/overview': {
      id: '/_dashboard/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logistics': {
      id: '/_dashboard/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof DashboardLogisticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fiscal': {
      id: '/_dashboard/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof DashboardFiscalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients': {
      id: '/_dashboard/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/channels': {
      id: '/_dashboard/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof DashboardChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/catalog': {
      id: '/_dashboard/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof DashboardCatalogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/tiktok': {
      id: '/api/webhooks/tiktok'
      path: '/api/webhooks/tiktok'
      fullPath: '/api/webhooks/tiktok'
      preLoaderRoute: typeof ApiWebhooksTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/shopify': {
      id: '/api/webhooks/shopify'
      path: '/api/webhooks/shopify'
      fullPath: '/api/webhooks/shopify'
      preLoaderRoute: typeof ApiWebhooksShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/shopee': {
      id: '/api/webhooks/shopee'
      path: '/api/webhooks/shopee'
      fullPath: '/api/webhooks/shopee'
      preLoaderRoute: typeof ApiWebhooksShopeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/pagar-me': {
      id: '/api/webhooks/pagar-me'
      path: '/api/webhooks/pagar-me'
      fullPath: '/api/webhooks/pagar-me'
      preLoaderRoute: typeof ApiWebhooksPagarMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/nuvemshop': {
      id: '/api/webhooks/nuvemshop'
      path: '/api/webhooks/nuvemshop'
      fullPath: '/api/webhooks/nuvemshop'
      preLoaderRoute: typeof ApiWebhooksNuvemshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercado-pago': {
      id: '/api/webhooks/mercado-pago'
      path: '/api/webhooks/mercado-pago'
      fullPath: '/api/webhooks/mercado-pago'
      preLoaderRoute: typeof ApiWebhooksMercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercado-livre': {
      id: '/api/webhooks/mercado-livre'
      path: '/api/webhooks/mercado-livre'
      fullPath: '/api/webhooks/mercado-livre'
      preLoaderRoute: typeof ApiWebhooksMercadoLivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/melhor-envio': {
      id: '/api/webhooks/melhor-envio'
      path: '/api/webhooks/melhor-envio'
      fullPath: '/api/webhooks/melhor-envio'
      preLoaderRoute: typeof ApiWebhooksMelhorEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/instagram': {
      id: '/api/webhooks/instagram'
      path: '/api/webhooks/instagram'
      fullPath: '/api/webhooks/instagram'
      preLoaderRoute: typeof ApiWebhooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/evolution': {
      id: '/api/webhooks/evolution'
      path: '/api/webhooks/evolution'
      fullPath: '/api/webhooks/evolution'
      preLoaderRoute: typeof ApiWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/amazon': {
      id: '/api/webhooks/amazon'
      path: '/api/webhooks/amazon'
      fullPath: '/api/webhooks/amazon'
      preLoaderRoute: typeof ApiWebhooksAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/run': {
      id: '/api/cron/run'
      path: '/api/cron/run'
      fullPath: '/api/cron/run'
      preLoaderRoute: typeof ApiCronRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/logistics/warehouse': {
      id: '/_dashboard/logistics/warehouse'
      path: '/warehouse'
      fullPath: '/logistics/warehouse'
      preLoaderRoute: typeof DashboardLogisticsWarehouseRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/tracking': {
      id: '/_dashboard/logistics/tracking'
      path: '/tracking'
      fullPath: '/logistics/tracking'
      preLoaderRoute: typeof DashboardLogisticsTrackingRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/sla': {
      id: '/_dashboard/logistics/sla'
      path: '/sla'
      fullPath: '/logistics/sla'
      preLoaderRoute: typeof DashboardLogisticsSlaRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/returns': {
      id: '/_dashboard/logistics/returns'
      path: '/returns'
      fullPath: '/logistics/returns'
      preLoaderRoute: typeof DashboardLogisticsReturnsRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/receiving': {
      id: '/_dashboard/logistics/receiving'
      path: '/receiving'
      fullPath: '/logistics/receiving'
      preLoaderRoute: typeof DashboardLogisticsReceivingRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/quarantine': {
      id: '/_dashboard/logistics/quarantine'
      path: '/quarantine'
      fullPath: '/logistics/quarantine'
      preLoaderRoute: typeof DashboardLogisticsQuarantineRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/products': {
      id: '/_dashboard/logistics/products'
      path: '/products'
      fullPath: '/logistics/products'
      preLoaderRoute: typeof DashboardLogisticsProductsRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/pickups': {
      id: '/_dashboard/logistics/pickups'
      path: '/pickups'
      fullPath: '/logistics/pickups'
      preLoaderRoute: typeof DashboardLogisticsPickupsRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/picking': {
      id: '/_dashboard/logistics/picking'
      path: '/picking'
      fullPath: '/logistics/picking'
      preLoaderRoute: typeof DashboardLogisticsPickingRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/packing': {
      id: '/_dashboard/logistics/packing'
      path: '/packing'
      fullPath: '/logistics/packing'
      preLoaderRoute: typeof DashboardLogisticsPackingRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/ops-dashboard': {
      id: '/_dashboard/logistics/ops-dashboard'
      path: '/ops-dashboard'
      fullPath: '/logistics/ops-dashboard'
      preLoaderRoute: typeof DashboardLogisticsOpsDashboardRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/inventory': {
      id: '/_dashboard/logistics/inventory'
      path: '/inventory'
      fullPath: '/logistics/inventory'
      preLoaderRoute: typeof DashboardLogisticsInventoryRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/incidents': {
      id: '/_dashboard/logistics/incidents'
      path: '/incidents'
      fullPath: '/logistics/incidents'
      preLoaderRoute: typeof DashboardLogisticsIncidentsRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/dispatch': {
      id: '/_dashboard/logistics/dispatch'
      path: '/dispatch'
      fullPath: '/logistics/dispatch'
      preLoaderRoute: typeof DashboardLogisticsDispatchRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/carriers': {
      id: '/_dashboard/logistics/carriers'
      path: '/carriers'
      fullPath: '/logistics/carriers'
      preLoaderRoute: typeof DashboardLogisticsCarriersRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/logistics/analytics': {
      id: '/_dashboard/logistics/analytics'
      path: '/analytics'
      fullPath: '/logistics/analytics'
      preLoaderRoute: typeof DashboardLogisticsAnalyticsRouteImport
      parentRoute: typeof DashboardLogisticsRoute
    }
    '/_dashboard/fiscal/config': {
      id: '/_dashboard/fiscal/config'
      path: '/config'
      fullPath: '/fiscal/config'
      preLoaderRoute: typeof DashboardFiscalConfigRouteImport
      parentRoute: typeof DashboardFiscalRoute
    }
    '/_dashboard/fiscal/$id': {
      id: '/_dashboard/fiscal/$id'
      path: '/$id'
      fullPath: '/fiscal/$id'
      preLoaderRoute: typeof DashboardFiscalIdRouteImport
      parentRoute: typeof DashboardFiscalRoute
    }
    '/_dashboard/clients/$id': {
      id: '/_dashboard/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardClientsRoute
    }
    '/_dashboard/channels/tiktok': {
      id: '/_dashboard/channels/tiktok'
      path: '/tiktok'
      fullPath: '/channels/tiktok'
      preLoaderRoute: typeof DashboardChannelsTiktokRouteImport
      parentRoute: typeof DashboardChannelsRoute
    }
    '/_dashboard/channels/shopee': {
      id: '/_dashboard/channels/shopee'
      path: '/shopee'
      fullPath: '/channels/shopee'
      preLoaderRoute: typeof DashboardChannelsShopeeRouteImport
      parentRoute: typeof DashboardChannelsRoute
    }
    '/_dashboard/channels/mercado-livre': {
      id: '/_dashboard/channels/mercado-livre'
      path: '/mercado-livre'
      fullPath: '/channels/mercado-livre'
      preLoaderRoute: typeof DashboardChannelsMercadoLivreRouteImport
      parentRoute: typeof DashboardChannelsRoute
    }
    '/_dashboard/channels/lojas': {
      id: '/_dashboard/channels/lojas'
      path: '/lojas'
      fullPath: '/channels/lojas'
      preLoaderRoute: typeof DashboardChannelsLojasRouteImport
      parentRoute: typeof DashboardChannelsRoute
    }
    '/_dashboard/channels/instagram': {
      id: '/_dashboard/channels/instagram'
      path: '/instagram'
      fullPath: '/channels/instagram'
      preLoaderRoute: typeof DashboardChannelsInstagramRouteImport
      parentRoute: typeof DashboardChannelsRoute
    }
    '/_dashboard/channels/amazon': {
      id: '/_dashboard/channels/amazon'
      path: '/amazon'
      fullPath: '/channels/amazon'
      preLoaderRoute: typeof DashboardChannelsAmazonRouteImport
      parentRoute: typeof DashboardChannelsRoute
    }
    '/_dashboard/catalog/fiscal': {
      id: '/_dashboard/catalog/fiscal'
      path: '/fiscal'
      fullPath: '/catalog/fiscal'
      preLoaderRoute: typeof DashboardCatalogFiscalRouteImport
      parentRoute: typeof DashboardCatalogRoute
    }
    '/api/oauth/whatsapp/callback': {
      id: '/api/oauth/whatsapp/callback'
      path: '/api/oauth/whatsapp/callback'
      fullPath: '/api/oauth/whatsapp/callback'
      preLoaderRoute: typeof ApiOauthWhatsappCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/tiktok/callback': {
      id: '/api/oauth/tiktok/callback'
      path: '/api/oauth/tiktok/callback'
      fullPath: '/api/oauth/tiktok/callback'
      preLoaderRoute: typeof ApiOauthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/shopify/callback': {
      id: '/api/oauth/shopify/callback'
      path: '/api/oauth/shopify/callback'
      fullPath: '/api/oauth/shopify/callback'
      preLoaderRoute: typeof ApiOauthShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/shopee/callback': {
      id: '/api/oauth/shopee/callback'
      path: '/api/oauth/shopee/callback'
      fullPath: '/api/oauth/shopee/callback'
      preLoaderRoute: typeof ApiOauthShopeeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/nuvemshop/callback': {
      id: '/api/oauth/nuvemshop/callback'
      path: '/api/oauth/nuvemshop/callback'
      fullPath: '/api/oauth/nuvemshop/callback'
      preLoaderRoute: typeof ApiOauthNuvemshopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/meta/callback': {
      id: '/api/oauth/meta/callback'
      path: '/api/oauth/meta/callback'
      fullPath: '/api/oauth/meta/callback'
      preLoaderRoute: typeof ApiOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/mercado-livre/callback': {
      id: '/api/oauth/mercado-livre/callback'
      path: '/api/oauth/mercado-livre/callback'
      fullPath: '/api/oauth/mercado-livre/callback'
      preLoaderRoute: typeof ApiOauthMercadoLivreCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/melhor-envio/callback': {
      id: '/api/oauth/melhor-envio/callback'
      path: '/api/oauth/melhor-envio/callback'
      fullPath: '/api/oauth/melhor-envio/callback'
      preLoaderRoute: typeof ApiOauthMelhorEnvioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/instagram/callback': {
      id: '/api/oauth/instagram/callback'
      path: '/api/oauth/instagram/callback'
      fullPath: '/api/oauth/instagram/callback'
      preLoaderRoute: typeof ApiOauthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/amazon/callback': {
      id: '/api/oauth/amazon/callback'
      path: '/api/oauth/amazon/callback'
      fullPath: '/api/oauth/amazon/callback'
      preLoaderRoute: typeof ApiOauthAmazonCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardCatalogRouteChildren {
  DashboardCatalogFiscalRoute: typeof DashboardCatalogFiscalRoute
}

const DashboardCatalogRouteChildren: DashboardCatalogRouteChildren = {
  DashboardCatalogFiscalRoute: DashboardCatalogFiscalRoute,
}

const DashboardCatalogRouteWithChildren =
  DashboardCatalogRoute._addFileChildren(DashboardCatalogRouteChildren)

interface DashboardChannelsRouteChildren {
  DashboardChannelsAmazonRoute: typeof DashboardChannelsAmazonRoute
  DashboardChannelsInstagramRoute: typeof DashboardChannelsInstagramRoute
  DashboardChannelsLojasRoute: typeof DashboardChannelsLojasRoute
  DashboardChannelsMercadoLivreRoute: typeof DashboardChannelsMercadoLivreRoute
  DashboardChannelsShopeeRoute: typeof DashboardChannelsShopeeRoute
  DashboardChannelsTiktokRoute: typeof DashboardChannelsTiktokRoute
}

const DashboardChannelsRouteChildren: DashboardChannelsRouteChildren = {
  DashboardChannelsAmazonRoute: DashboardChannelsAmazonRoute,
  DashboardChannelsInstagramRoute: DashboardChannelsInstagramRoute,
  DashboardChannelsLojasRoute: DashboardChannelsLojasRoute,
  DashboardChannelsMercadoLivreRoute: DashboardChannelsMercadoLivreRoute,
  DashboardChannelsShopeeRoute: DashboardChannelsShopeeRoute,
  DashboardChannelsTiktokRoute: DashboardChannelsTiktokRoute,
}

const DashboardChannelsRouteWithChildren =
  DashboardChannelsRoute._addFileChildren(DashboardChannelsRouteChildren)

interface DashboardClientsRouteChildren {
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
}

const DashboardClientsRouteChildren: DashboardClientsRouteChildren = {
  DashboardClientsIdRoute: DashboardClientsIdRoute,
}

const DashboardClientsRouteWithChildren =
  DashboardClientsRoute._addFileChildren(DashboardClientsRouteChildren)

interface DashboardFiscalRouteChildren {
  DashboardFiscalIdRoute: typeof DashboardFiscalIdRoute
  DashboardFiscalConfigRoute: typeof DashboardFiscalConfigRoute
}

const DashboardFiscalRouteChildren: DashboardFiscalRouteChildren = {
  DashboardFiscalIdRoute: DashboardFiscalIdRoute,
  DashboardFiscalConfigRoute: DashboardFiscalConfigRoute,
}

const DashboardFiscalRouteWithChildren = DashboardFiscalRoute._addFileChildren(
  DashboardFiscalRouteChildren,
)

interface DashboardLogisticsRouteChildren {
  DashboardLogisticsAnalyticsRoute: typeof DashboardLogisticsAnalyticsRoute
  DashboardLogisticsCarriersRoute: typeof DashboardLogisticsCarriersRoute
  DashboardLogisticsDispatchRoute: typeof DashboardLogisticsDispatchRoute
  DashboardLogisticsIncidentsRoute: typeof DashboardLogisticsIncidentsRoute
  DashboardLogisticsInventoryRoute: typeof DashboardLogisticsInventoryRoute
  DashboardLogisticsOpsDashboardRoute: typeof DashboardLogisticsOpsDashboardRoute
  DashboardLogisticsPackingRoute: typeof DashboardLogisticsPackingRoute
  DashboardLogisticsPickingRoute: typeof DashboardLogisticsPickingRoute
  DashboardLogisticsPickupsRoute: typeof DashboardLogisticsPickupsRoute
  DashboardLogisticsProductsRoute: typeof DashboardLogisticsProductsRoute
  DashboardLogisticsQuarantineRoute: typeof DashboardLogisticsQuarantineRoute
  DashboardLogisticsReceivingRoute: typeof DashboardLogisticsReceivingRoute
  DashboardLogisticsReturnsRoute: typeof DashboardLogisticsReturnsRoute
  DashboardLogisticsSlaRoute: typeof DashboardLogisticsSlaRoute
  DashboardLogisticsTrackingRoute: typeof DashboardLogisticsTrackingRoute
  DashboardLogisticsWarehouseRoute: typeof DashboardLogisticsWarehouseRoute
}

const DashboardLogisticsRouteChildren: DashboardLogisticsRouteChildren = {
  DashboardLogisticsAnalyticsRoute: DashboardLogisticsAnalyticsRoute,
  DashboardLogisticsCarriersRoute: DashboardLogisticsCarriersRoute,
  DashboardLogisticsDispatchRoute: DashboardLogisticsDispatchRoute,
  DashboardLogisticsIncidentsRoute: DashboardLogisticsIncidentsRoute,
  DashboardLogisticsInventoryRoute: DashboardLogisticsInventoryRoute,
  DashboardLogisticsOpsDashboardRoute: DashboardLogisticsOpsDashboardRoute,
  DashboardLogisticsPackingRoute: DashboardLogisticsPackingRoute,
  DashboardLogisticsPickingRoute: DashboardLogisticsPickingRoute,
  DashboardLogisticsPickupsRoute: DashboardLogisticsPickupsRoute,
  DashboardLogisticsProductsRoute: DashboardLogisticsProductsRoute,
  DashboardLogisticsQuarantineRoute: DashboardLogisticsQuarantineRoute,
  DashboardLogisticsReceivingRoute: DashboardLogisticsReceivingRoute,
  DashboardLogisticsReturnsRoute: DashboardLogisticsReturnsRoute,
  DashboardLogisticsSlaRoute: DashboardLogisticsSlaRoute,
  DashboardLogisticsTrackingRoute: DashboardLogisticsTrackingRoute,
  DashboardLogisticsWarehouseRoute: DashboardLogisticsWarehouseRoute,
}

const DashboardLogisticsRouteWithChildren =
  DashboardLogisticsRoute._addFileChildren(DashboardLogisticsRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCatalogRoute: typeof DashboardCatalogRouteWithChildren
  DashboardChannelsRoute: typeof DashboardChannelsRouteWithChildren
  DashboardClientsRoute: typeof DashboardClientsRouteWithChildren
  DashboardFiscalRoute: typeof DashboardFiscalRouteWithChildren
  DashboardLogisticsRoute: typeof DashboardLogisticsRouteWithChildren
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardRetentionRoute: typeof DashboardRetentionRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuccessRoute: typeof DashboardSuccessRoute
  DashboardTrafficRoute: typeof DashboardTrafficRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCatalogRoute: DashboardCatalogRouteWithChildren,
  DashboardChannelsRoute: DashboardChannelsRouteWithChildren,
  DashboardClientsRoute: DashboardClientsRouteWithChildren,
  DashboardFiscalRoute: DashboardFiscalRouteWithChildren,
  DashboardLogisticsRoute: DashboardLogisticsRouteWithChildren,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardRetentionRoute: DashboardRetentionRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuccessRoute: DashboardSuccessRoute,
  DashboardTrafficRoute: DashboardTrafficRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OpsRouteChildren {
  OpsDispatchRoute: typeof OpsDispatchRoute
  OpsPackingRoute: typeof OpsPackingRoute
  OpsPickingRoute: typeof OpsPickingRoute
  OpsReceivingRoute: typeof OpsReceivingRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsDispatchRoute: OpsDispatchRoute,
  OpsPackingRoute: OpsPackingRoute,
  OpsPickingRoute: OpsPickingRoute,
  OpsReceivingRoute: OpsReceivingRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface PortalRouteChildren {
  PortalAnalyticsRoute: typeof PortalAnalyticsRoute
  PortalCatalogRoute: typeof PortalCatalogRoute
  PortalLogisticsRoute: typeof PortalLogisticsRoute
  PortalLoyaltyRoute: typeof PortalLoyaltyRoute
  PortalOverviewRoute: typeof PortalOverviewRoute
  PortalRetentionRoute: typeof PortalRetentionRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalTrafficRoute: typeof PortalTrafficRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAnalyticsRoute: PortalAnalyticsRoute,
  PortalCatalogRoute: PortalCatalogRoute,
  PortalLogisticsRoute: PortalLogisticsRoute,
  PortalLoyaltyRoute: PortalLoyaltyRoute,
  PortalOverviewRoute: PortalOverviewRoute,
  PortalRetentionRoute: PortalRetentionRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalTrafficRoute: PortalTrafficRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  MinhaContaTokenRoute: MinhaContaTokenRoute,
  ApiCronRunRoute: ApiCronRunRoute,
  ApiWebhooksAmazonRoute: ApiWebhooksAmazonRoute,
  ApiWebhooksEvolutionRoute: ApiWebhooksEvolutionRoute,
  ApiWebhooksInstagramRoute: ApiWebhooksInstagramRoute,
  ApiWebhooksMelhorEnvioRoute: ApiWebhooksMelhorEnvioRoute,
  ApiWebhooksMercadoLivreRoute: ApiWebhooksMercadoLivreRoute,
  ApiWebhooksMercadoPagoRoute: ApiWebhooksMercadoPagoRoute,
  ApiWebhooksNuvemshopRoute: ApiWebhooksNuvemshopRoute,
  ApiWebhooksPagarMeRoute: ApiWebhooksPagarMeRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
  ApiWebhooksShopeeRoute: ApiWebhooksShopeeRoute,
  ApiWebhooksShopifyRoute: ApiWebhooksShopifyRoute,
  ApiWebhooksTiktokRoute: ApiWebhooksTiktokRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
  ApiOauthAmazonCallbackRoute: ApiOauthAmazonCallbackRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthInstagramCallbackRoute: ApiOauthInstagramCallbackRoute,
  ApiOauthMelhorEnvioCallbackRoute: ApiOauthMelhorEnvioCallbackRoute,
  ApiOauthMercadoLivreCallbackRoute: ApiOauthMercadoLivreCallbackRoute,
  ApiOauthMetaCallbackRoute: ApiOauthMetaCallbackRoute,
  ApiOauthNuvemshopCallbackRoute: ApiOauthNuvemshopCallbackRoute,
  ApiOauthShopeeCallbackRoute: ApiOauthShopeeCallbackRoute,
  ApiOauthShopifyCallbackRoute: ApiOauthShopifyCallbackRoute,
  ApiOauthTiktokCallbackRoute: ApiOauthTiktokCallbackRoute,
  ApiOauthWhatsappCallbackRoute: ApiOauthWhatsappCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
