/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTrafficRouteImport } from './routes/portal.traffic'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalRetentionRouteImport } from './routes/portal.retention'
import { Route as PortalOverviewRouteImport } from './routes/portal.overview'
import { Route as PortalLogisticsRouteImport } from './routes/portal.logistics'
import { Route as DashboardTrafficRouteImport } from './routes/_dashboard.traffic'
import { Route as DashboardSuccessRouteImport } from './routes/_dashboard.success'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardRetentionRouteImport } from './routes/_dashboard.retention'
import { Route as DashboardOverviewRouteImport } from './routes/_dashboard.overview'
import { Route as DashboardLogisticsRouteImport } from './routes/_dashboard.logistics'
import { Route as DashboardFiscalRouteImport } from './routes/_dashboard.fiscal'
import { Route as DashboardClientsRouteImport } from './routes/_dashboard.clients'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as ApiWebhooksShopifyRouteImport } from './routes/api/webhooks/shopify'
import { Route as ApiWebhooksShopeeRouteImport } from './routes/api/webhooks/shopee'
import { Route as ApiWebhooksNuvemshopRouteImport } from './routes/api/webhooks/nuvemshop'
import { Route as ApiWebhooksMercadoLivreRouteImport } from './routes/api/webhooks/mercado-livre'
import { Route as ApiWebhooksMelhorEnvioRouteImport } from './routes/api/webhooks/melhor-envio'
import { Route as DashboardFiscalConfigRouteImport } from './routes/_dashboard.fiscal.config'
import { Route as DashboardClientsIdRouteImport } from './routes/_dashboard.clients.$id'
import { Route as ApiOauthShopifyCallbackRouteImport } from './routes/api/oauth/shopify/callback'
import { Route as ApiOauthShopeeCallbackRouteImport } from './routes/api/oauth/shopee/callback'
import { Route as ApiOauthNuvemshopCallbackRouteImport } from './routes/api/oauth/nuvemshop/callback'
import { Route as ApiOauthMetaCallbackRouteImport } from './routes/api/oauth/meta/callback'
import { Route as ApiOauthMercadoLivreCallbackRouteImport } from './routes/api/oauth/mercado-livre/callback'
import { Route as ApiOauthMelhorEnvioCallbackRouteImport } from './routes/api/oauth/melhor-envio/callback'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google/callback'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTrafficRoute = PortalTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRetentionRoute = PortalRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOverviewRoute = PortalOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLogisticsRoute = PortalLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardTrafficRoute = DashboardTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuccessRoute = DashboardSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRetentionRoute = DashboardRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogisticsRoute = DashboardLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFiscalRoute = DashboardFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWebhooksShopifyRoute = ApiWebhooksShopifyRouteImport.update({
  id: '/api/webhooks/shopify',
  path: '/api/webhooks/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksShopeeRoute = ApiWebhooksShopeeRouteImport.update({
  id: '/api/webhooks/shopee',
  path: '/api/webhooks/shopee',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksNuvemshopRoute = ApiWebhooksNuvemshopRouteImport.update({
  id: '/api/webhooks/nuvemshop',
  path: '/api/webhooks/nuvemshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadoLivreRoute = ApiWebhooksMercadoLivreRouteImport.update({
  id: '/api/webhooks/mercado-livre',
  path: '/api/webhooks/mercado-livre',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMelhorEnvioRoute = ApiWebhooksMelhorEnvioRouteImport.update({
  id: '/api/webhooks/melhor-envio',
  path: '/api/webhooks/melhor-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFiscalConfigRoute = DashboardFiscalConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardFiscalRoute,
} as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardClientsRoute,
} as any)
const ApiOauthShopifyCallbackRoute = ApiOauthShopifyCallbackRouteImport.update({
  id: '/api/oauth/shopify/callback',
  path: '/api/oauth/shopify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthShopeeCallbackRoute = ApiOauthShopeeCallbackRouteImport.update({
  id: '/api/oauth/shopee/callback',
  path: '/api/oauth/shopee/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthNuvemshopCallbackRoute =
  ApiOauthNuvemshopCallbackRouteImport.update({
    id: '/api/oauth/nuvemshop/callback',
    path: '/api/oauth/nuvemshop/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthMetaCallbackRoute = ApiOauthMetaCallbackRouteImport.update({
  id: '/api/oauth/meta/callback',
  path: '/api/oauth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthMercadoLivreCallbackRoute =
  ApiOauthMercadoLivreCallbackRouteImport.update({
    id: '/api/oauth/mercado-livre/callback',
    path: '/api/oauth/mercado-livre/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthMelhorEnvioCallbackRoute =
  ApiOauthMelhorEnvioCallbackRouteImport.update({
    id: '/api/oauth/melhor-envio/callback',
    path: '/api/oauth/melhor-envio/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/analytics': typeof DashboardAnalyticsRoute
  '/clients': typeof DashboardClientsRouteWithChildren
  '/fiscal': typeof DashboardFiscalRouteWithChildren
  '/logistics': typeof DashboardLogisticsRoute
  '/overview': typeof DashboardOverviewRoute
  '/retention': typeof DashboardRetentionRoute
  '/settings': typeof DashboardSettingsRoute
  '/success': typeof DashboardSuccessRoute
  '/traffic': typeof DashboardTrafficRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/overview': typeof PortalOverviewRoute
  '/portal/retention': typeof PortalRetentionRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/traffic': typeof PortalTrafficRoute
  '/clients/$id': typeof DashboardClientsIdRoute
  '/fiscal/config': typeof DashboardFiscalConfigRoute
  '/api/webhooks/melhor-envio': typeof ApiWebhooksMelhorEnvioRoute
  '/api/webhooks/mercado-livre': typeof ApiWebhooksMercadoLivreRoute
  '/api/webhooks/nuvemshop': typeof ApiWebhooksNuvemshopRoute
  '/api/webhooks/shopee': typeof ApiWebhooksShopeeRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/melhor-envio/callback': typeof ApiOauthMelhorEnvioCallbackRoute
  '/api/oauth/mercado-livre/callback': typeof ApiOauthMercadoLivreCallbackRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/nuvemshop/callback': typeof ApiOauthNuvemshopCallbackRoute
  '/api/oauth/shopee/callback': typeof ApiOauthShopeeCallbackRoute
  '/api/oauth/shopify/callback': typeof ApiOauthShopifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/analytics': typeof DashboardAnalyticsRoute
  '/clients': typeof DashboardClientsRouteWithChildren
  '/fiscal': typeof DashboardFiscalRouteWithChildren
  '/logistics': typeof DashboardLogisticsRoute
  '/overview': typeof DashboardOverviewRoute
  '/retention': typeof DashboardRetentionRoute
  '/settings': typeof DashboardSettingsRoute
  '/success': typeof DashboardSuccessRoute
  '/traffic': typeof DashboardTrafficRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/overview': typeof PortalOverviewRoute
  '/portal/retention': typeof PortalRetentionRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/traffic': typeof PortalTrafficRoute
  '/clients/$id': typeof DashboardClientsIdRoute
  '/fiscal/config': typeof DashboardFiscalConfigRoute
  '/api/webhooks/melhor-envio': typeof ApiWebhooksMelhorEnvioRoute
  '/api/webhooks/mercado-livre': typeof ApiWebhooksMercadoLivreRoute
  '/api/webhooks/nuvemshop': typeof ApiWebhooksNuvemshopRoute
  '/api/webhooks/shopee': typeof ApiWebhooksShopeeRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/melhor-envio/callback': typeof ApiOauthMelhorEnvioCallbackRoute
  '/api/oauth/mercado-livre/callback': typeof ApiOauthMercadoLivreCallbackRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/nuvemshop/callback': typeof ApiOauthNuvemshopCallbackRoute
  '/api/oauth/shopee/callback': typeof ApiOauthShopeeCallbackRoute
  '/api/oauth/shopify/callback': typeof ApiOauthShopifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/_dashboard/fiscal': typeof DashboardFiscalRouteWithChildren
  '/_dashboard/logistics': typeof DashboardLogisticsRoute
  '/_dashboard/overview': typeof DashboardOverviewRoute
  '/_dashboard/retention': typeof DashboardRetentionRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/success': typeof DashboardSuccessRoute
  '/_dashboard/traffic': typeof DashboardTrafficRoute
  '/portal/logistics': typeof PortalLogisticsRoute
  '/portal/overview': typeof PortalOverviewRoute
  '/portal/retention': typeof PortalRetentionRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/traffic': typeof PortalTrafficRoute
  '/_dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/_dashboard/fiscal/config': typeof DashboardFiscalConfigRoute
  '/api/webhooks/melhor-envio': typeof ApiWebhooksMelhorEnvioRoute
  '/api/webhooks/mercado-livre': typeof ApiWebhooksMercadoLivreRoute
  '/api/webhooks/nuvemshop': typeof ApiWebhooksNuvemshopRoute
  '/api/webhooks/shopee': typeof ApiWebhooksShopeeRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/melhor-envio/callback': typeof ApiOauthMelhorEnvioCallbackRoute
  '/api/oauth/mercado-livre/callback': typeof ApiOauthMercadoLivreCallbackRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/nuvemshop/callback': typeof ApiOauthNuvemshopCallbackRoute
  '/api/oauth/shopee/callback': typeof ApiOauthShopeeCallbackRoute
  '/api/oauth/shopify/callback': typeof ApiOauthShopifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/analytics'
    | '/clients'
    | '/fiscal'
    | '/logistics'
    | '/overview'
    | '/retention'
    | '/settings'
    | '/success'
    | '/traffic'
    | '/portal/logistics'
    | '/portal/overview'
    | '/portal/retention'
    | '/portal/settings'
    | '/portal/traffic'
    | '/clients/$id'
    | '/fiscal/config'
    | '/api/webhooks/melhor-envio'
    | '/api/webhooks/mercado-livre'
    | '/api/webhooks/nuvemshop'
    | '/api/webhooks/shopee'
    | '/api/webhooks/shopify'
    | '/api/oauth/google/callback'
    | '/api/oauth/melhor-envio/callback'
    | '/api/oauth/mercado-livre/callback'
    | '/api/oauth/meta/callback'
    | '/api/oauth/nuvemshop/callback'
    | '/api/oauth/shopee/callback'
    | '/api/oauth/shopify/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/analytics'
    | '/clients'
    | '/fiscal'
    | '/logistics'
    | '/overview'
    | '/retention'
    | '/settings'
    | '/success'
    | '/traffic'
    | '/portal/logistics'
    | '/portal/overview'
    | '/portal/retention'
    | '/portal/settings'
    | '/portal/traffic'
    | '/clients/$id'
    | '/fiscal/config'
    | '/api/webhooks/melhor-envio'
    | '/api/webhooks/mercado-livre'
    | '/api/webhooks/nuvemshop'
    | '/api/webhooks/shopee'
    | '/api/webhooks/shopify'
    | '/api/oauth/google/callback'
    | '/api/oauth/melhor-envio/callback'
    | '/api/oauth/mercado-livre/callback'
    | '/api/oauth/meta/callback'
    | '/api/oauth/nuvemshop/callback'
    | '/api/oauth/shopee/callback'
    | '/api/oauth/shopify/callback'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/portal'
    | '/_dashboard/analytics'
    | '/_dashboard/clients'
    | '/_dashboard/fiscal'
    | '/_dashboard/logistics'
    | '/_dashboard/overview'
    | '/_dashboard/retention'
    | '/_dashboard/settings'
    | '/_dashboard/success'
    | '/_dashboard/traffic'
    | '/portal/logistics'
    | '/portal/overview'
    | '/portal/retention'
    | '/portal/settings'
    | '/portal/traffic'
    | '/_dashboard/clients/$id'
    | '/_dashboard/fiscal/config'
    | '/api/webhooks/melhor-envio'
    | '/api/webhooks/mercado-livre'
    | '/api/webhooks/nuvemshop'
    | '/api/webhooks/shopee'
    | '/api/webhooks/shopify'
    | '/api/oauth/google/callback'
    | '/api/oauth/melhor-envio/callback'
    | '/api/oauth/mercado-livre/callback'
    | '/api/oauth/meta/callback'
    | '/api/oauth/nuvemshop/callback'
    | '/api/oauth/shopee/callback'
    | '/api/oauth/shopify/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ApiWebhooksMelhorEnvioRoute: typeof ApiWebhooksMelhorEnvioRoute
  ApiWebhooksMercadoLivreRoute: typeof ApiWebhooksMercadoLivreRoute
  ApiWebhooksNuvemshopRoute: typeof ApiWebhooksNuvemshopRoute
  ApiWebhooksShopeeRoute: typeof ApiWebhooksShopeeRoute
  ApiWebhooksShopifyRoute: typeof ApiWebhooksShopifyRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthMelhorEnvioCallbackRoute: typeof ApiOauthMelhorEnvioCallbackRoute
  ApiOauthMercadoLivreCallbackRoute: typeof ApiOauthMercadoLivreCallbackRoute
  ApiOauthMetaCallbackRoute: typeof ApiOauthMetaCallbackRoute
  ApiOauthNuvemshopCallbackRoute: typeof ApiOauthNuvemshopCallbackRoute
  ApiOauthShopeeCallbackRoute: typeof ApiOauthShopeeCallbackRoute
  ApiOauthShopifyCallbackRoute: typeof ApiOauthShopifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/traffic': {
      id: '/portal/traffic'
      path: '/traffic'
      fullPath: '/portal/traffic'
      preLoaderRoute: typeof PortalTrafficRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/retention': {
      id: '/portal/retention'
      path: '/retention'
      fullPath: '/portal/retention'
      preLoaderRoute: typeof PortalRetentionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/overview': {
      id: '/portal/overview'
      path: '/overview'
      fullPath: '/portal/overview'
      preLoaderRoute: typeof PortalOverviewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/logistics': {
      id: '/portal/logistics'
      path: '/logistics'
      fullPath: '/portal/logistics'
      preLoaderRoute: typeof PortalLogisticsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_dashboard/traffic': {
      id: '/_dashboard/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof DashboardTrafficRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/success': {
      id: '/_dashboard/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof DashboardSuccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/retention': {
      id: '/_dashboard/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof DashboardRetentionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/overview': {
      id: '/_dashboard/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logistics': {
      id: '/_dashboard/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof DashboardLogisticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fiscal': {
      id: '/_dashboard/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof DashboardFiscalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients': {
      id: '/_dashboard/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/shopify': {
      id: '/api/webhooks/shopify'
      path: '/api/webhooks/shopify'
      fullPath: '/api/webhooks/shopify'
      preLoaderRoute: typeof ApiWebhooksShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/shopee': {
      id: '/api/webhooks/shopee'
      path: '/api/webhooks/shopee'
      fullPath: '/api/webhooks/shopee'
      preLoaderRoute: typeof ApiWebhooksShopeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/nuvemshop': {
      id: '/api/webhooks/nuvemshop'
      path: '/api/webhooks/nuvemshop'
      fullPath: '/api/webhooks/nuvemshop'
      preLoaderRoute: typeof ApiWebhooksNuvemshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercado-livre': {
      id: '/api/webhooks/mercado-livre'
      path: '/api/webhooks/mercado-livre'
      fullPath: '/api/webhooks/mercado-livre'
      preLoaderRoute: typeof ApiWebhooksMercadoLivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/melhor-envio': {
      id: '/api/webhooks/melhor-envio'
      path: '/api/webhooks/melhor-envio'
      fullPath: '/api/webhooks/melhor-envio'
      preLoaderRoute: typeof ApiWebhooksMelhorEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/fiscal/config': {
      id: '/_dashboard/fiscal/config'
      path: '/config'
      fullPath: '/fiscal/config'
      preLoaderRoute: typeof DashboardFiscalConfigRouteImport
      parentRoute: typeof DashboardFiscalRoute
    }
    '/_dashboard/clients/$id': {
      id: '/_dashboard/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardClientsRoute
    }
    '/api/oauth/shopify/callback': {
      id: '/api/oauth/shopify/callback'
      path: '/api/oauth/shopify/callback'
      fullPath: '/api/oauth/shopify/callback'
      preLoaderRoute: typeof ApiOauthShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/shopee/callback': {
      id: '/api/oauth/shopee/callback'
      path: '/api/oauth/shopee/callback'
      fullPath: '/api/oauth/shopee/callback'
      preLoaderRoute: typeof ApiOauthShopeeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/nuvemshop/callback': {
      id: '/api/oauth/nuvemshop/callback'
      path: '/api/oauth/nuvemshop/callback'
      fullPath: '/api/oauth/nuvemshop/callback'
      preLoaderRoute: typeof ApiOauthNuvemshopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/meta/callback': {
      id: '/api/oauth/meta/callback'
      path: '/api/oauth/meta/callback'
      fullPath: '/api/oauth/meta/callback'
      preLoaderRoute: typeof ApiOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/mercado-livre/callback': {
      id: '/api/oauth/mercado-livre/callback'
      path: '/api/oauth/mercado-livre/callback'
      fullPath: '/api/oauth/mercado-livre/callback'
      preLoaderRoute: typeof ApiOauthMercadoLivreCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/melhor-envio/callback': {
      id: '/api/oauth/melhor-envio/callback'
      path: '/api/oauth/melhor-envio/callback'
      fullPath: '/api/oauth/melhor-envio/callback'
      preLoaderRoute: typeof ApiOauthMelhorEnvioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardClientsRouteChildren {
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
}

const DashboardClientsRouteChildren: DashboardClientsRouteChildren = {
  DashboardClientsIdRoute: DashboardClientsIdRoute,
}

const DashboardClientsRouteWithChildren =
  DashboardClientsRoute._addFileChildren(DashboardClientsRouteChildren)

interface DashboardFiscalRouteChildren {
  DashboardFiscalConfigRoute: typeof DashboardFiscalConfigRoute
}

const DashboardFiscalRouteChildren: DashboardFiscalRouteChildren = {
  DashboardFiscalConfigRoute: DashboardFiscalConfigRoute,
}

const DashboardFiscalRouteWithChildren = DashboardFiscalRoute._addFileChildren(
  DashboardFiscalRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardClientsRoute: typeof DashboardClientsRouteWithChildren
  DashboardFiscalRoute: typeof DashboardFiscalRouteWithChildren
  DashboardLogisticsRoute: typeof DashboardLogisticsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardRetentionRoute: typeof DashboardRetentionRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuccessRoute: typeof DashboardSuccessRoute
  DashboardTrafficRoute: typeof DashboardTrafficRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardClientsRoute: DashboardClientsRouteWithChildren,
  DashboardFiscalRoute: DashboardFiscalRouteWithChildren,
  DashboardLogisticsRoute: DashboardLogisticsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardRetentionRoute: DashboardRetentionRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuccessRoute: DashboardSuccessRoute,
  DashboardTrafficRoute: DashboardTrafficRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PortalRouteChildren {
  PortalLogisticsRoute: typeof PortalLogisticsRoute
  PortalOverviewRoute: typeof PortalOverviewRoute
  PortalRetentionRoute: typeof PortalRetentionRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalTrafficRoute: typeof PortalTrafficRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalLogisticsRoute: PortalLogisticsRoute,
  PortalOverviewRoute: PortalOverviewRoute,
  PortalRetentionRoute: PortalRetentionRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalTrafficRoute: PortalTrafficRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ApiWebhooksMelhorEnvioRoute: ApiWebhooksMelhorEnvioRoute,
  ApiWebhooksMercadoLivreRoute: ApiWebhooksMercadoLivreRoute,
  ApiWebhooksNuvemshopRoute: ApiWebhooksNuvemshopRoute,
  ApiWebhooksShopeeRoute: ApiWebhooksShopeeRoute,
  ApiWebhooksShopifyRoute: ApiWebhooksShopifyRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthMelhorEnvioCallbackRoute: ApiOauthMelhorEnvioCallbackRoute,
  ApiOauthMercadoLivreCallbackRoute: ApiOauthMercadoLivreCallbackRoute,
  ApiOauthMetaCallbackRoute: ApiOauthMetaCallbackRoute,
  ApiOauthNuvemshopCallbackRoute: ApiOauthNuvemshopCallbackRoute,
  ApiOauthShopeeCallbackRoute: ApiOauthShopeeCallbackRoute,
  ApiOauthShopifyCallbackRoute: ApiOauthShopifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
