/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTrafficRouteImport } from './routes/_dashboard.traffic'
import { Route as DashboardSuccessRouteImport } from './routes/_dashboard.success'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardRetentionRouteImport } from './routes/_dashboard.retention'
import { Route as DashboardOverviewRouteImport } from './routes/_dashboard.overview'
import { Route as DashboardLogisticsRouteImport } from './routes/_dashboard.logistics'
import { Route as DashboardFiscalRouteImport } from './routes/_dashboard.fiscal'
import { Route as DashboardClientsRouteImport } from './routes/_dashboard.clients'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as DashboardFiscalConfigRouteImport } from './routes/_dashboard.fiscal.config'
import { Route as DashboardClientsIdRouteImport } from './routes/_dashboard.clients.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrafficRoute = DashboardTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuccessRoute = DashboardSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRetentionRoute = DashboardRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogisticsRoute = DashboardLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFiscalRoute = DashboardFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFiscalConfigRoute = DashboardFiscalConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardFiscalRoute,
} as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/clients': typeof DashboardClientsRouteWithChildren
  '/fiscal': typeof DashboardFiscalRouteWithChildren
  '/logistics': typeof DashboardLogisticsRoute
  '/overview': typeof DashboardOverviewRoute
  '/retention': typeof DashboardRetentionRoute
  '/settings': typeof DashboardSettingsRoute
  '/success': typeof DashboardSuccessRoute
  '/traffic': typeof DashboardTrafficRoute
  '/clients/$id': typeof DashboardClientsIdRoute
  '/fiscal/config': typeof DashboardFiscalConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/clients': typeof DashboardClientsRouteWithChildren
  '/fiscal': typeof DashboardFiscalRouteWithChildren
  '/logistics': typeof DashboardLogisticsRoute
  '/overview': typeof DashboardOverviewRoute
  '/retention': typeof DashboardRetentionRoute
  '/settings': typeof DashboardSettingsRoute
  '/success': typeof DashboardSuccessRoute
  '/traffic': typeof DashboardTrafficRoute
  '/clients/$id': typeof DashboardClientsIdRoute
  '/fiscal/config': typeof DashboardFiscalConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/_dashboard/fiscal': typeof DashboardFiscalRouteWithChildren
  '/_dashboard/logistics': typeof DashboardLogisticsRoute
  '/_dashboard/overview': typeof DashboardOverviewRoute
  '/_dashboard/retention': typeof DashboardRetentionRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/success': typeof DashboardSuccessRoute
  '/_dashboard/traffic': typeof DashboardTrafficRoute
  '/_dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/_dashboard/fiscal/config': typeof DashboardFiscalConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/clients'
    | '/fiscal'
    | '/logistics'
    | '/overview'
    | '/retention'
    | '/settings'
    | '/success'
    | '/traffic'
    | '/clients/$id'
    | '/fiscal/config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/clients'
    | '/fiscal'
    | '/logistics'
    | '/overview'
    | '/retention'
    | '/settings'
    | '/success'
    | '/traffic'
    | '/clients/$id'
    | '/fiscal/config'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/analytics'
    | '/_dashboard/clients'
    | '/_dashboard/fiscal'
    | '/_dashboard/logistics'
    | '/_dashboard/overview'
    | '/_dashboard/retention'
    | '/_dashboard/settings'
    | '/_dashboard/success'
    | '/_dashboard/traffic'
    | '/_dashboard/clients/$id'
    | '/_dashboard/fiscal/config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/traffic': {
      id: '/_dashboard/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof DashboardTrafficRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/success': {
      id: '/_dashboard/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof DashboardSuccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/retention': {
      id: '/_dashboard/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof DashboardRetentionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/overview': {
      id: '/_dashboard/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logistics': {
      id: '/_dashboard/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof DashboardLogisticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fiscal': {
      id: '/_dashboard/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof DashboardFiscalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients': {
      id: '/_dashboard/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fiscal/config': {
      id: '/_dashboard/fiscal/config'
      path: '/config'
      fullPath: '/fiscal/config'
      preLoaderRoute: typeof DashboardFiscalConfigRouteImport
      parentRoute: typeof DashboardFiscalRoute
    }
    '/_dashboard/clients/$id': {
      id: '/_dashboard/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardClientsRoute
    }
  }
}

interface DashboardClientsRouteChildren {
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
}

const DashboardClientsRouteChildren: DashboardClientsRouteChildren = {
  DashboardClientsIdRoute: DashboardClientsIdRoute,
}

const DashboardClientsRouteWithChildren =
  DashboardClientsRoute._addFileChildren(DashboardClientsRouteChildren)

interface DashboardFiscalRouteChildren {
  DashboardFiscalConfigRoute: typeof DashboardFiscalConfigRoute
}

const DashboardFiscalRouteChildren: DashboardFiscalRouteChildren = {
  DashboardFiscalConfigRoute: DashboardFiscalConfigRoute,
}

const DashboardFiscalRouteWithChildren = DashboardFiscalRoute._addFileChildren(
  DashboardFiscalRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardClientsRoute: typeof DashboardClientsRouteWithChildren
  DashboardFiscalRoute: typeof DashboardFiscalRouteWithChildren
  DashboardLogisticsRoute: typeof DashboardLogisticsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardRetentionRoute: typeof DashboardRetentionRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuccessRoute: typeof DashboardSuccessRoute
  DashboardTrafficRoute: typeof DashboardTrafficRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardClientsRoute: DashboardClientsRouteWithChildren,
  DashboardFiscalRoute: DashboardFiscalRouteWithChildren,
  DashboardLogisticsRoute: DashboardLogisticsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardRetentionRoute: DashboardRetentionRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuccessRoute: DashboardSuccessRoute,
  DashboardTrafficRoute: DashboardTrafficRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
