// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztaozvgmzycetiwwkhjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0YW96dmdtenljZXRpd3draGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5NzY5ODAsImV4cCI6MjA5NjU1Mjk4MH0.VSLtRexv1DPpiJiySwv7Xl7G8gV6ezULO6FWuoS4x-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});